version: "3"

services:
  php-nginx:
    build:
      context: ./php-nginx
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "30000-30050:30000-30050"
    networks:
      - internal
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=pepa

networks:
  internal:
    driver: bridge